const Comment = require('../Models/Comment');

const sampleComments = [
  "Messi 🇦🇷",
  "Messiii 💙",
  "Messi 🐐",
  "Messi 🇦🇷🔥",
  "Messi always 🐐",
  "Messi ❤️",
  "Messiiii",
  "Messi 🇦🇷🐐",
  "Leo Messi 🇦🇷",
  "Leo 🐐",
  "Lionel Messi ❤️",
  "Lionel Messi 🇦🇷",
  "Lionel 🇦🇷🐐",
  "GOAT Messi 🐐",
  "Messi 🔥🔥",
  "Messi 🙌",
  "Messi forever 💙",
  "Messi king 👑",
  "Messi the GOAT 🐐",
  "Messi 🇦🇷❤️🔥",
  "Leo ❤️",
  "Leo 🇦🇷",
  "Leo Messi 🐐",
  "Messiii🐐🇦🇷",
  "Messi my GOAT",
  "MESSI 🇦🇷",
  "Messi 🏆",
  "Messi 🐐🔥",
  "Messi 💙🇦🇷",
  "Messi ❤️🐐",
  "Neymar 🇧🇷",
  "Neymar Jr 🇧🇷",
  "Ney 🔥",
  "Ney ❤️",
  "Neymar 🔥🔥🔥",
  "Neymar Jr 💛💚",
  "Ney 🇧🇷❤️",
  "Neymar 🐐",
  "Neymar ❤️🔥",
  "Ney 🇧🇷",
  "Neymar forever",
  "Neymar Jr 👑",
  "Neymar ❤️🇧🇷",
  "Ney 🔥🇧🇷",
  "Neymar 💙",
  "Neymar Jr 🔥",
  "NEYMAR 🇧🇷",
  "Ney 🐐",
  "Neymar 💛💚🔥",
  "Neymar Jr ❤️",
  "Cristiano 🇵🇹",
  "Cristiano Ronaldo 🐐",
  "CR7 ❤️",
  "CR7 🔥",
  "Ronaldo 🇵🇹",
  "Cristiano 👑",
  "CR7 GOAT",
  "Cristiano 🐐🇵🇹",
  "Siuuuuu",
  "SIUUUU 🔥",
  "CR7 Forever",
  "Cristiano ❤️🇵🇹",
  "GOAT CR7",
  "Ronaldo 🐐",
  "Cristiano Ronaldo ❤️",
  "SIUUUUUU",
  "CR7 🙌",
  "Cristiano 🔥🔥",
  "Ronaldo ❤️",
  "Portugal 🇵🇹",
  "Mbappe 🇫🇷",
  "Mbappe 🔥",
  "Kylian ❤️",
  "Mbappe ⚡",
  "Mbappe 🐐",
  "Mbappe 🇫🇷🔥",
  "Mbappe ❤️🇫🇷",
  "Kylian Mbappe",
  "Mbappe GOAT",
  "Mbappe 💙",
  "Haaland 🇳🇴",
  "Haaland ⚽",
  "Haaland 🔥",
  "Erling Haaland",
  "Haaland 👑",
  "Haaland ❤️",
  "Haaland 💙",
  "Erling 🔥",
  "Haaland 🐐",
  "Norway 🇳🇴",
  "Lamine Yamal ⭐",
  "Yamal 🔥",
  "Yamal ❤️",
  "Lamine 🇪🇸",
  "Yamal 👏",
  "Yamal 🐐",
  "Lamine Yamal ❤️",
  "Yamal 💙❤️",
  "Yamal 🇪🇸🔥",
  "Pedri 💙❤️",
  "Pedri 🇪🇸",
  "Pedri 🔥",
  "Pedri ❤️",
  "Pedri 👏",
  "Gavi ❤️",
  "Gavi 🔥",
  "Gavi 💙❤️",
  "Barcelona 💙❤️",
  "Barca ❤️💙",
  "Visca Barca 💙❤️",
  "Barca 🔥",
  "Forca Barca",
  "Barcelona 🔥🔥",
  "Barca forever",
  "Real Madrid 🤍",
  "Hala Madrid 🤍",
  "Madrid ❤️",
  "Real Madrid 👑",
  "Hala Madrid 🔥",
  "Madrid 🤍🔥",
  "Madrid forever",
  "Vini Jr 🔥",
  "Vinicius ❤️",
  "Vini 🇧🇷",
  "Vini Jr 🐐",
  "Vinicius Jr 🔥",
  "Bellingham ❤️",
  "Jude Bellingham",
  "Bellingham 🔥",
  "Jude 👑",
  "Jude ❤️",
  "Argentina 🇦🇷",
  "Argentina ❤️",
  "Vamos Argentina 🇦🇷",
  "Argentina 🔥",
  "🇦🇷🐐",
  "🇦🇷❤️",
  "🇦🇷🔥",
  "🇵🇹🔥",
  "🇧🇷🔥",
  "🇫🇷🔥",
  "⚽❤️",
  "⚽🔥",
  "🐐🐐",
  "🔥🔥🔥",
  "❤️❤️❤️",
  "👏👏👏",
  "🙌🙌",
  "King 👑",
  "GOAT 🐐",
  "Best player ❤️",
  "Legend 🔥",
  "Amazing ❤️",
  "Top player 🔥",
  "Love this ❤️",
  "So good 🔥",
  "Winner 🏆",
  "Congratulations 🎉",
  "Let's go 🔥",
  "Amazing reel ❤️",
  "Awesome 🔥",
  "Great content 👏",
  "Keep it up 🔥",
  "Fantastic ❤️",
  "Love this post ❤️",
  "Big fan 🔥",
  "Always support ❤️",
  "Number one 🐐",
  "Best ever 🔥",
  "Respect 👏",
  "Legend forever ❤️",
  "Pure class 🔥",
  "Incredible 👏",
  "Masterclass ⚽",
  "Football ❤️",
  "Best footballer 🐐",
  "My idol ❤️",
  "Always the GOAT 🐐",
  "Let's win 🔥",
  "Hope I win ❤️",
  "Pick me 🙏",
  "Good luck everyone 🍀",
  "Good luck ❤️",
  "I need this 🔥",
  "Dream giveaway ❤️",
  "Amazing giveaway 🎉",
  "Thank you ❤️",
  "Thanks 🔥",
  "Count me in 🙌",
  "Done ✅",
  "Done ❤️",
  "Participated ✅",
  "Joined 🔥",
  "Entered ❤️",
  "Let's gooo 🔥",
  "Winner loading 🏆",
  "Hope to win 🤞",
  "Crossing fingers 🤞",
  "Wish me luck 🍀",
  "Fingers crossed 🤞",
  "Amazing prize ❤️",
  "Love your page ❤️",
  "Supporting always 🙌",
  "Best giveaway ever 🎉",
  "Thank you so much ❤️"
];

const seedComments = async () => {
  try {
    const count = await Comment.countDocuments();
    if (count === 0) {
      console.log('[seedComments] Comment collection is empty. Seeding sample comments...');
      
      const documents = sampleComments.map(text => ({ text }));
      await Comment.insertMany(documents);
      
      console.log(`[seedComments] Successfully seeded ${documents.length} sample comments!`);
    } else {
      console.log(`[seedComments] Comment collection already has ${count} records. Skipping seed.`);
    }
  } catch (error) {
    console.error('[seedComments] Error seeding comments:', error.message);
  }
};

module.exports = seedComments;
